# Site settings
title: "Acewind - Unrivaled Security & Protection"
email: sales@acewind.com
description: "Unrivaled Security & Protection"
baseurl: "" 
url: "https://acewind.com"

# Gems
gems:
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-redirect-from
 #- jekyll-assets

# Build settings
markdown: kramdown
paginate: 5
paginate_path: 'page:num/'
permalink: pretty

exclude:
  - CNAME
  - README
  - Gemfile
  - "*.cmd"

sass:
    style: compressed